### ISSUE TITLE
Trying to run at desk

### ISSUE THREAD

**Issue by Ecleptic** [notea-org/notea#144] opened 2022-09-14 20:12 UTC
When running the application, I get this error and googling does not seem to help me get around it. 

```
{
  name: 'NoSuchKey',
  message: 'The specified key does not exist.',
  status: 500,
  stack: 'NoSuchKey: The specified key does not exist.\n' +
    '    at deserializeAws_restXmlNoSuchKeyResponse (~/projects/notea/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:6154:23)\n' +
    '    at deserializeAws_restXmlGetObjectCommandError (~/projects/notea/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4353:25)\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n' +
    '    at async ~/projects/notea/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24\n' +
    '    at async ~/projects/notea/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20\n' +
    '    at async StandardRetryStrategy.retry (~/projects/notea/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)\n' +
    '    at async ~/projects/notea/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:56:20\n' +
    '    at async ~/projects/notea/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22\n' +
    '    at async StoreS3.getObject (webpack-internal:///(api)/./libs/server/store/providers/s3.ts:82:28)'
}
```

**Comment by tecc** [comment] 2022-09-14 20:19
That's interesting. What object storage software are you using?
I'm guessing it could be fixed by changing [line 18 in libs/server/store.ts](https://github.com/notea-org/notea/blob/e853f121aa48e22d156515df98de2fd522f4f58c/libs/server/store/providers/s3.ts#L18) to include `err.name`, but I may be entirely wrong.

**Comment by Ecleptic** [comment] 2022-09-14 20:21
All I've done is the steps in the readme: 
`docker-compose up -d`
`yarn dev`

I assume it's a volume permission issue? I am not terribly familiar with docker.

**Comment by Ecleptic** [comment] 2022-09-14 20:34
changing line 18 to include err.name did help me create a file, however typing in the body got me a new error. Which I am looking up now. 
![SCR-20220914-lhi](https://user-images.githubusercontent.com/3928224/190256832-a92b76aa-13f1-4ec0-a07b-91b192888490.jpg)

**Comment by Ecleptic** [comment] 2022-09-14 20:43
What version of node do you use?

**Comment by tecc** [comment] 2022-09-14 20:45
I use node 16.

**Comment by Ecleptic** [comment] 2022-09-14 20:47
That wasn't it. 😆

**Comment by Ecleptic** [comment] 2022-09-14 21:00
we may need to update node packages to address this.

**Comment by tecc** [comment] 2022-09-14 21:08
Perhaps. I'll have to properly look into it later, since I'm slightly busy at the moment.

**Comment by tecc** [comment] 2022-09-22 08:58
Okay, update on this issue: Since I can't test it myself at this moment, I wonder if downgrading `prosemirrror-model` to `^1.8.1` - I perused a bit through the lockfiles of both `rich-markdown-editor` and Notea, and it might be caused by having a too new version for the editor library.
The main reason I'm suggesting this is that `rich-markdown-editor` has been archived for nearly a year, and as such may not work with the later versions of Prosemirror.
If not that, it might be that the prosemirror versions used are incompatible with each other.
This is all speculative though.

**Comment by tecc** [comment] 2022-09-24 12:32
Quick update on this issue: I tested it with the changes I made in #146, and it works fine.

**Closed** 2022-09-24 12:34 UTC
Labels: bug
